language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'
  -
git:
  depth: 3

script:
  - yarn test

notifications:
  slack:
    secure: "wY4SfqwBkt43AKhnK4KRSR1K96vrdZOZv3M5bgaCOxBjt2tvsxA7LNY/wFWtf1CvV1UzU1M+/d/VKfWgF/oDIMblTRzwanQMBcqmIDcfRiqNVg0o805l3sIbVelTtbGJWchGlxCrwaPyYq5vZRI6U1JH4VsAq7TS4N2fTSwoKBzeUSbHgYOZ2qt9j4Nw9qJn9P2iwgDD3wQ2k/4XYYFhb0+qOAwRthtSQ11hvNjNbijoukzLWSw5qouyTaL6Ep88qKN8gijV6o5oxXpgMws37r2xL2gVzVHZHnTcA6JPbGNbVhJ+bMsWY8xP3dOuBFDoDm2ECs+Mv0y+6cTSypspB9RpdXrqZ/sswFIJ7ndOP0NSZH7mAHgFcX2ddZRe/VL1jeCLoks56ohOPF7GCVaLgmnGhpnQ7cE/JQzxAewQATRP4c6Q/TB2iCN4KgcpY4Iyn63WLBk0wRfH3vtxMrStAuUHtgPX0PGs+914sNj+V5Ani1+qrRFhgfUBGJzVTxC+OSlSTatAkiPv5kKbxamodFdGlBjXzZKWrJ9Bz68aL6QyQ48VNr6hbZDbbVeI1y4VDPjATAMgcI3yDsidT2iuAoGuByPrQZvuXJ9iHp4V70ieqdG54EJP1L01Qzk+cdFIiBllQ/XsddsyIsCKeNpw0dLBNYFVz73skw5VGktk+9o="
  email:
    recipients:
      - acortez.dev@gmail.com
    on_success: always
    on_failure: always

deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key:
    secure: "mYQ9kuO3Ks2NtDnbsr63xVxZoGo1MJ5roM9eRR9OvLJbVOTxOmqh3hikVe/XUMzPcrZZ/Y0e2vlU7p0KiDXNpKRt+c3dV9qrgFiACVJkUaR2mxJhOOAYM4LG/u2qmr5RzInLjRqViiw/RnBjbciwxZ+hvz3TH3hldFjYGtF4VGTe4nahiVoben6SCjqXB8RPp6Pfx17pKSgS/oXIc6OVdVygfABTgQqTW9vts7S4Ed8sC14e3fK7+00b96pVUl9tpEdMyBzZJUenihNx+anwbAjaPmqjHRm1r725m/d0ENQgbgFOYoLhXzEMJFYDIERuRlK0OT9Dxmq4TdxLyyBe3GQlnwqDTt1ZSL1Xl7/IuiY7FAtzpIxMOqbJ6CPha8QeUlgVVvS0rTcJ9LfIlOl0WWQ2jd3ZHBv46Q2QxXS8VZPY4tfQmtJ4nbRaKP0VnD/ejX4bvSxFLuARg0CJ4mRc83Y+0+pX/EwtZPs44lTD1xctcA2uclBQvisGm0Z0L32DIQCtgMhfj4v+hqtJcE/fUPSoka12Sm47Wz9YidXrGJgS4a7b66hWgOgUy9ql2yXik07HJpv7q7yBoa9boz+QR4dHSLRy9smhC6bVbqq6BihI2ZSypm/5VEobLJHmnoomuY+Af4rmYH4QTeGe74v8KT/zqgXHvKjhhH2TFHGZTnM="
  app: react-store-backend
  on:
    repo: zikeron/platzi-store-backend
