language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'
  -
git:
  depth: 3

script:
  - yarn test

notifications:
  slack:
    secure: "wY4SfqwBkt43AKhnK4KRSR1K96vrdZOZv3M5bgaCOxBjt2tvsxA7LNY/wFWtf1CvV1UzU1M+/d/VKfWgF/oDIMblTRzwanQMBcqmIDcfRiqNVg0o805l3sIbVelTtbGJWchGlxCrwaPyYq5vZRI6U1JH4VsAq7TS4N2fTSwoKBzeUSbHgYOZ2qt9j4Nw9qJn9P2iwgDD3wQ2k/4XYYFhb0+qOAwRthtSQ11hvNjNbijoukzLWSw5qouyTaL6Ep88qKN8gijV6o5oxXpgMws37r2xL2gVzVHZHnTcA6JPbGNbVhJ+bMsWY8xP3dOuBFDoDm2ECs+Mv0y+6cTSypspB9RpdXrqZ/sswFIJ7ndOP0NSZH7mAHgFcX2ddZRe/VL1jeCLoks56ohOPF7GCVaLgmnGhpnQ7cE/JQzxAewQATRP4c6Q/TB2iCN4KgcpY4Iyn63WLBk0wRfH3vtxMrStAuUHtgPX0PGs+914sNj+V5Ani1+qrRFhgfUBGJzVTxC+OSlSTatAkiPv5kKbxamodFdGlBjXzZKWrJ9Bz68aL6QyQ48VNr6hbZDbbVeI1y4VDPjATAMgcI3yDsidT2iuAoGuByPrQZvuXJ9iHp4V70ieqdG54EJP1L01Qzk+cdFIiBllQ/XsddsyIsCKeNpw0dLBNYFVz73skw5VGktk+9o="
  email:
    recipients:
      - acortez.dev@gmail.com
    on_success: always
    on_failure: always

deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: "XR0p/mwctiC1hV0BnuUhx5QdrrPzVFFkyO9Jl4TNEpSW3zIU0ZurDcNfL9p5Kchy7L953KJIc3L9ksm8q+TpHdnaTPby6yBbURRcpYTyqW0U7Mgnjl+6ujEgnXwFEPDO67MKOt7URsxy8VzAU0d0iNkcWDylPSBTEPQ5LFpVhJY/DEjuYRHED0Fbh6LNvGe5UtyfRK4OZFC6gZAdCpWrBtBwOhMSUJY3guw0eKmh9y5a5L36eEJnvQWrGlO3rbo7rXNf4LirYvlm2+E25Nn0KLtW+qy8PmcoYGnhWvSUGj7wxUwMAvDJGoAQAvm2NbOMOtKNSN/WfJ4XoZTEYw3zBuywcG/wbTOhpEMVlFiK23lS9OWG6UqYuAdMvW/Lsqv+Wpg/3Hiw6exG+jRCWxlMUqa4JmhQYeK3dIFOG+OCLbSSTct/AYLDaiA4LQwGrebhhRjnGYSDkfHEnWAdyrwDW5EqAG7EcJRnURW9W5MLWF3Atjva69GdWTxDVNI6qryfUCUN2vlJK74LxEaQDqjIozDXNx+6mqJZXTao26quunN36i2krB3Q+Wp3+BfdtA+9mavp3ssAPw1vZ5bTpNVR/jrj6QExuEAjswPxXpNBezAHxlxvylinwRcG7MXTf8wrc5FPUTE/HIVWo+QW1QP2mnQXEGk1LeMdoeXOksiGNzw="
  app: react-store-backend
  on:
    repo: zikeron/platzi-store-backend
