language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'
  - 
git:
  depth: 3

script:
  - yarn test

notifications:
  slack:
    secure: "e8pU2O4Uz52kr1lvAomVkhUvuGdqA22xyP2B40//mXLx/edzhGY5o7o8SG0S//83I23QA2UvbWSa6DzadTtU2uuumWrT4A38ZpD5WZp6fdz9zY6arjfuPR3HLKlhF0lKiXsIVBrEkSqSkcbq2C0YgqNUbkIaQtnS/TYonzPJ3k5lM+9BSXqAqu4LUKbxYBjhHR/7DMiksuTvEPm+fZ1nCTp6hgeBR18L+i+o78InlfLrWKehiVLPwd8HXHQEpqf/fRa1vsMnzSDuavMx8NlMhvtskGrMZRKXnfV2jJrFs+Z2NSshbCc37CbHBQ5jaLK2lzQ1il9Dj5bQKH5UzADtQC8+avnXlwPgmoaUEKZyhhOEdMGkJ2E+4BmfjHeB8bGBxYDpgd5IiQ+Sak1BsvSI7o5cl0WgAnbW51soGOwT10sm11rbSYC4Hf+wkWx4JnnzTVWx+8BUTtPMAxt6WxJnAK79RAQ9G/RIrX838+S6RWB6H6wEGIjtHYljHmR4GN7o8V5SvH3wPwEMRQjNKG1wn4TGAwEzYJFjFKbEiXKpoWJv9xWGoTGW39uWx2f4GPptKnD5SrsUkTjB5BiR+IJ1PXI+pHbWJnyBVc3ud14OpQbeMbrYsmmrCTWullXXNrxdgPxZHwl3TjkwOM21NAf2rRrzX5HtaX41yC+WnBGFOIw="
  email:
    recipients:
      - acortez.dev@gmail.com
    on_success: always
    on_failure: always

deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: "XR0p/mwctiC1hV0BnuUhx5QdrrPzVFFkyO9Jl4TNEpSW3zIU0ZurDcNfL9p5Kchy7L953KJIc3L9ksm8q+TpHdnaTPby6yBbURRcpYTyqW0U7Mgnjl+6ujEgnXwFEPDO67MKOt7URsxy8VzAU0d0iNkcWDylPSBTEPQ5LFpVhJY/DEjuYRHED0Fbh6LNvGe5UtyfRK4OZFC6gZAdCpWrBtBwOhMSUJY3guw0eKmh9y5a5L36eEJnvQWrGlO3rbo7rXNf4LirYvlm2+E25Nn0KLtW+qy8PmcoYGnhWvSUGj7wxUwMAvDJGoAQAvm2NbOMOtKNSN/WfJ4XoZTEYw3zBuywcG/wbTOhpEMVlFiK23lS9OWG6UqYuAdMvW/Lsqv+Wpg/3Hiw6exG+jRCWxlMUqa4JmhQYeK3dIFOG+OCLbSSTct/AYLDaiA4LQwGrebhhRjnGYSDkfHEnWAdyrwDW5EqAG7EcJRnURW9W5MLWF3Atjva69GdWTxDVNI6qryfUCUN2vlJK74LxEaQDqjIozDXNx+6mqJZXTao26quunN36i2krB3Q+Wp3+BfdtA+9mavp3ssAPw1vZ5bTpNVR/jrj6QExuEAjswPxXpNBezAHxlxvylinwRcG7MXTf8wrc5FPUTE/HIVWo+QW1QP2mnQXEGk1LeMdoeXOksiGNzw="
  app: react-store-backend
  on:
    repo: zikeron/platzi-store-backend
